#!/usr/bin/env python
"""
This script allows for sending ingest messages to edex

usage: ingestsender [-h] queue message sensor delivery_type deployment_number

positional arguments:
  queue              The ingest queue to send the message to
  message            The data file or message to send
  sensor             The sensor type of the data file
  delivery_type      The delivery type, e.g. telemetered or recovered
  deployment_number  The deployment number of the data file

optional arguments:
  -h, --help         show this help message and exit



Example usage:
 ./ingestsender Ingest.ctdgv_m_glider_recovered /home/ekladstrup/Downloads/CP05MOAS-GL001/cp_374_2014_105_1_0.full.mrg CP05MOAS-GL001-99-CTDGV9999 recovered 1
"""

from ingest import QpidSender

import argparse

parser = argparse.ArgumentParser()
parser.add_argument("queue", help="The ingest queue to send the message to")
parser.add_argument("message", help="The data file or message to send")
parser.add_argument("sensor", help="The sensor type of the data file")
parser.add_argument("delivery_type", help="The delivery type, e.g. telemetered or recovered")
parser.add_argument("deployment_number", help="The deployment number of the data file")
args = parser.parse_args()

qpid_sender = QpidSender(address=args.address)
qpid_sender.connect()
qpidSender.send(args.message, "text/plain", args.sensor, arg.delivery_type, args.deployment_number)
