# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ingesting', 'ingesting'), ('ingested', 'ingested')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_mask', models.CharField(max_length=255)),
                ('uframe_route', models.CharField(max_length=255)),
                ('reference_designator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('csv_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.DataSourceType')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_designator', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Platform'),
        ),
        migrations.AddField(
            model_name='datagroup',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.DataSourceType'),
        ),
        migrations.AddField(
            model_name='datagroup',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_groups', to='deployments.Deployment'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='data_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.DataGroup'),
        ),
    ]
