# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'ingest_start', b'Ingestion Started'), (b'ingest_end', b'Ingestion Ended'), (b'ingest_prov', b'Ingestion Provenance'), (b'ingest_part_count', b'Ingestion Particle Count'), (b'ingest_error', b'Ingestion Error')], max_length=255)),
                ('level', models.CharField(choices=[(b'INFO', b'Info'), (b'ERROR', b'Error'), (b'WARN', b'Warn'), (b'DEBUG', b'Debug'), (b'NA', b'N/A')], max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('route', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('subsite', models.CharField(blank=True, max_length=255, null=True)),
                ('node', models.CharField(blank=True, max_length=255, null=True)),
                ('sensor', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('deployment', models.IntegerField(blank=True, null=True)),
                ('parser_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parser_version', models.CharField(blank=True, max_length=255, null=True)),
                ('particle_count', models.IntegerField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
